{
  description = "This is my translatable kitty configuration. ChatGPT helped me make this.";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
  };

  outputs = { self, nixpkgs, ... }:
  let
    system = "x86_64-linux";
    pkgs = import nixpkgs { inherit system; };

    background = pkgs.fetchurl {
      url = "https://gruvbox-wallpapers.pages.dev/wallpapers/anime/5m5kLI9.png";
      sha256 = "sha256-utmDMNeSzboGyup3+0N8hjk8/wgiFctuWYD4u/JptxE=";
    };

    font = pkgs.fetchurl {
      url = "https://codeberg.org/juarez-gonza/dotconfig/src/commit/8b811a305389ceab8bd0d03052e0c3e7c62bfe1e/gui/fonts/LigaComicMono.ttf";
      sha256 = "sha256-HVWy+71cpI6vXUKywOTgNIxi3yrgFKeYYLH9X2rZ7is=";
    };

    theme = pkgs.fetchFromGitHub {
      owner = "wdomitrz";
      repo = "kitty_gruvbox_theme";
      rev = "b60d532";
      sha256 = "sha256-JKeGIwwkwBGdbRh8jOGgMz4MDl7ycymfSnBsnzNL/ik=";
    };

    configuration = ''
# Autogenerated kitty.conf from flake.nix
# The point is that people should just run `nix run` or `nix build` instead of manual paste

include ${theme}/gruvbox_dark_soft.conf

# I am not a psychopath for using ligatures and comic sans monospaced
# You just dont get it
font_family	${font}
font_size	14

# font_family		    FiraCode-Retina
# {bold,italic,bold_italic}_font FiraCode-{Bold,Light,SemiBold}

cursor_shape		      block
cursor_blink_interval	0

mouse_hide_wait	-1

tab_title_template " ┇ {fmt.fg.tab}{index}:{num_windows} {tab.active_exe} ● {title} λ"
tab_bar_style		powerline
tab_powerline_style	angled

#shell /usr/bin/zsh

background_image ${background}
background_image_layout cscaled
background_tint 0.85
background_blur 10

editor vim

map alt+t new_tab
map alt+h previous_tab
map alt+l next_tab
map alt+q close_tab

# Background
background_image ${background}
    '';

  in {
    packages.${system}.default = pkgs.writeText "kitty.conf" configuration;
  }
}
